fix(aws-msk-mcp-server): Readmefix for prerequisite section (#848)
* feat aws msk mcp server

* Documentation updates

* update create to be more descriptive

* feat aws msk mcp server

* Following instructions in readMe, have NOT written tests though

* higher level updates as described in readME

* Fix installation configuration in readme
Added tests

* fix readMe (browse by building and working)
feat readonly mode

* fix server name and instructions
added pydantic typechecks and optional typehints

* fix list_configs
feat cursor deeplink install
added entry to mkdocks and codeowners

* fix main_test

* updated owner
Fixed the pyrighttests

* update codeowners

* Update src/aws-msk-mcp-server/README.md

Co-authored-by: alexa-perlov <56009415+alexa-perlov@users.noreply.github.com>

* add test coverage for clustertelemetry

* Tests to increase coverage

* update codeowners
fix failing tests

* update codeowners
fix failing tests

* fix tests and coverage

* update tests to increase coverage

* feat serverless
fix test coverage

* remove xml file

* reran coverage tests

* remove xml file again

* Pydantic Field, deleted coverage.sml, fixed install button

* fix cluster_arn default pydantic arg

* user_agent_extra for all tools

* readme reformatting

* fix tests

* Set default flag to allow writes

* fix readme for consistency

* fix: test coverage for mutate_config, read_cluster_init

* fix: added aws msk docasaurus md

* fix: docusaurus consistency

* fix: install scripts and readMe error

* fix: readme correction for cursor link and markdown text

* fix: add line to readme to end formatting

* docs: clarify the correct server run command (#810)

* Update README.md with correct server run command

Following current documentation I'm getting:
error: Failed to spawn: `server.py`
  Caused by: No such file or directory (os error 2)

* Update README.md as requested with uv

Using uv instead of python directly

---------

Co-authored-by: Scott Schreckengaust <scottschreckengaust@users.noreply.github.com>

* feat(aws-dataprocessing-mcp-server): Add Common resource handler for S3 and IAM tools required for Glue, EMR and Athena (#817)

* feat(aws-dataprocessing-mcp-server):Add Common resource handler for S3 and IAM tools required for Glue, EMR and Athena

* chore(aws-dataprocessing-mcp-server): Add more unit test cases for common_resource_handler

* chore(aws-api-mcp-server): Add CHANGELOG entry for the initial release (#819)

Co-authored-by: Roman Shevchuk <rshev@amazon.com>

* fix(aws-api-mcp-server): update README.md (#821)

* Fix Cursor button

* Fix JSON formatting

* docs(aws-api-mcp-server): update release year (#822)

Co-authored-by: Roman Shevchuk <rshev@amazon.com>

* Add AWS API MCP server as part of the issue templates (#820)

Co-authored-by: Claudiu Popa <clpo@amazon.com>
Co-authored-by: alexa-perlov <56009415+alexa-perlov@users.noreply.github.com>

* chore(aws-pricing-mcp-server): Doc updates and dependency upgrades (#809)

* chore: Upgrade dependencies

* docs: Update blog link

* docs: Update installation and add pricing tag

---------

Co-authored-by: alexa-perlov <56009415+alexa-perlov@users.noreply.github.com>
Co-authored-by: Scott Schreckengaust <scottschreckengaust@users.noreply.github.com>

* Automatic update of packages

* add codeowner and fix versioning

* revert comments

* prerequisite section missing from src readme

* remove comment from server.py for unspported feature

---------

Co-authored-by: alexa-perlov <56009415+alexa-perlov@users.noreply.github.com>
Co-authored-by: Alain Krok <alkrok@amazon.com>
Co-authored-by: Scott Schreckengaust <scottschreckengaust@users.noreply.github.com>
Co-authored-by: Marat Galiev <kazanlug@gmail.com>
Co-authored-by: Vaibhav Naik <101835362+naikvaib@users.noreply.github.com>
Co-authored-by: Roman Shevchuk <roma.shev01@gmail.com>
Co-authored-by: Roman Shevchuk <rshev@amazon.com>
Co-authored-by: Arne Wouters <25950814+arnewouters@users.noreply.github.com>
Co-authored-by: Claudiu Popa <pcmanticore@gmail.com>
Co-authored-by: Claudiu Popa <clpo@amazon.com>
Co-authored-by: Nikolaus Spring <54682104+nspring00@users.noreply.github.com>
Co-authored-by: awslabs-mcp <203918161+awslabs-mcp@users.noreply.github.com>